server:
  port: 8080
spring:
  application:
    name: billingsystem
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/billingdb
    username: suresh
    password: demo#1
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
      springframework: info